config/routes.rb
Rails.application.routes.draw do

  resources :profiles

  resources :senders
  resources :roles
  resources :statuses
  resources :packages

  devise_for :users

  root 'welcome#index'

  namespace :admin do
    root 'welcome#index'
    resources :packages
    resources :statuses
    resources :senders
    resources :roles
    resources :users
    resources :settings
  end

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  belongs_to :user
  belongs_to :role
end

app/models/package.rb
class Package < ActiveRecord::Base
	belongs_to :user
	belongs_to :sender
	has_many :statuses
	validates :reference, :track, presence: true
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :assignments
  has_many :users, :through => :assignments
end

app/models/sender.rb
class Sender < ActiveRecord::Base
	has_many :packages
	validates :name, :description, presence: true
end

app/models/setting.rb
class Setting < ActiveRecord::Base
end

app/models/status.rb
class Status < ActiveRecord::Base
	belongs_to :package
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :profile, dependent: :destroy
  has_many :assignments, dependent: :destroy
  has_many :roles, :through => :assignments
  has_many :packages	
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  after_create :create_profile

	def has_role?(role_sym)
  		roles.any? { |r| r.name.underscore.to_sym == role_sym }
	end

  private

  def create_profile
    Profile.create(user_id: self.id)
  end
	         
end

app/controllers/packages_controller.rb
class PackagesController < ApplicationController
  before_action :set_package, only: [:show, :edit, :update, :destroy]

  respond_to :html, :json

  def index
    @packages = current_user.packages
    respond_with(@packages)
  end

  def show
    @statuses = @package.statuses.order(date: :desc)    
    respond_with(@package)
  end

  def new
    @package = Package.new
    respond_with(@package)
  end

  def edit
  end

  def create
    @package = Package.new(package_params)
    flash[:notice] = 'Package was successfully created.' if @package.save
    respond_with(@package)
  end

  def update
    flash[:notice] = 'Package was successfully updated.' if @package.update(package_params)
    respond_with(@package)
  end

  def destroy
    @package.destroy
    respond_with(@package)
  end

  private
    def set_package
      @package = Package.find(params[:id])
    end

    def package_params
      params.require(:package).permit(:reference, :track, :date_received)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @profiles = Profile.all
    respond_with(@profiles)
  end

  def show
    respond_with(@profile)
  end

  def new
    @profile = Profile.new
    respond_with(@profile)
  end

  def edit
  end

  def create
    @profile = Profile.new(profile_params)
    flash[:notice] = 'Profile was successfully created.' if @profile.save
    respond_with(@profile)
  end

  def update
    flash[:notice] = 'Profile was successfully updated.' if @profile.update(profile_params)
    respond_with(@profile)
  end

  def destroy
    @profile.destroy
    respond_with(@profile)
  end

  private
    def set_profile
      @profile = Profile.find(params[:id])
    end

    def profile_params
      params.require(:profile).permit(:name, :address, :phone, :mobile, :fax, :zipcode, :city, :state, :country)
    end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @roles = Role.all
    respond_with(@roles)
  end

  def show
    respond_with(@role)
  end

  def new
    @role = Role.new
    respond_with(@role)
  end

  def edit
  end

  def create
    @role = Role.new(role_params)
    flash[:notice] = 'Role was successfully created.' if @role.save
    respond_with(@role)
  end

  def update
    flash[:notice] = 'Role was successfully updated.' if @role.update(role_params)
    respond_with(@role)
  end

  def destroy
    @role.destroy
    respond_with(@role)
  end

  private
    def set_role
      @role = Role.find(params[:id])
    end

    def role_params
      params.require(:role).permit(:name)
    end
end

app/controllers/senders_controller.rb
class SendersController < ApplicationController
  before_action :set_sender, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @senders = Sender.all
    respond_with(@senders)
  end

  def show
    respond_with(@sender)
  end

  def new
    @sender = Sender.new
    respond_with(@sender)
  end

  def edit
  end

  def create
    @sender = Sender.new(sender_params)
    flash[:notice] = 'Sender was successfully created.' if @sender.save
    respond_with(@sender)
  end

  def update
    flash[:notice] = 'Sender was successfully updated.' if @sender.update(sender_params)
    respond_with(@sender)
  end

  def destroy
    @sender.destroy
    respond_with(@sender)
  end

  private
    def set_sender
      @sender = Sender.find(params[:id])
    end

    def sender_params
      params.require(:sender).permit(:name, :description)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def company_name
		Setting.first.company_name
	end	
end

app/helpers/packages_helper.rb
module PackagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/senders_helper.rb
module SendersHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :address %><br>
    <%= f.text_area :address, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :phone %><br>
    <%= f.text_field :phone, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :mobile %><br>
    <%= f.text_field :mobile, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :fax %><br>
    <%= f.text_field :fax, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :zipcode %><br>
    <%= f.text_field :zipcode, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :city %><br>
    <%= f.text_field :city, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :state %><br>
    <%= f.text_field :state, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :country %><br>
    <%= f.text_field :country, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit 'Save', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1 class="page-header">Editing Account</h1>

<%= render 'form' %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Profiles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Mobile</th>
      <th>Fax</th>
      <th>Zipcode</th>
      <th>City</th>
      <th>State</th>
      <th>Country</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.name %></td>
        <td><%= profile.address %></td>
        <td><%= profile.phone %></td>
        <td><%= profile.mobile %></td>
        <td><%= profile.fax %></td>
        <td><%= profile.zipcode %></td>
        <td><%= profile.city %></td>
        <td><%= profile.state %></td>
        <td><%= profile.country %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<% if notice -%>
<div class="bs-component">
  <div class="alert alert-dismissable alert-success">
    <button type="button" class="close" data-dismiss="alert">×</button>
      <%= notice %>
    </div>
</div>
<% end -%>
<h1 class="page-header">Account</h1>

<div class="form-group">
<%= link_to 'Edit Account', edit_profile_path(@profile), :class => 'btn btn-primary' %>
</div>

<p>
  <strong>Name:</strong>
  <%= @profile.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @profile.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @profile.phone %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @profile.mobile %>
</p>

<p>
  <strong>Fax:</strong>
  <%= @profile.fax %>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= @profile.zipcode %>
</p>

<p>
  <strong>City:</strong>
  <%= @profile.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @profile.state %>
</p>

<p>
  <strong>Country:</strong>
  <%= @profile.country %>
</p>

app/views/roles/_form.html.erb
<%= form_for(@role) do |f| %>
  <% if @role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
      <% @role.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/roles/edit.html.erb
<h1>Editing Role</h1>

<%= render 'form' %>

<%= link_to 'Show', @role %> |
<%= link_to 'Back', roles_path %>

app/views/roles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Roles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @roles.each do |role| %>
      <tr>
        <td><%= role.name %></td>
        <td><%= link_to 'Show', role %></td>
        <td><%= link_to 'Edit', edit_role_path(role) %></td>
        <td><%= link_to 'Destroy', role, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Role', new_role_path %>

app/views/roles/new.html.erb
<h1>New Role</h1>

<%= render 'form' %>

<%= link_to 'Back', roles_path %>

app/views/roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @role.name %>
</p>

<%= link_to 'Edit', edit_role_path(@role) %> |
<%= link_to 'Back', roles_path %>