config/routes.rb
Rails.application.routes.draw do

  resources :profiles

  resources :senders
  resources :roles
  resources :statuses
  resources :packages

  devise_for :users

  root 'welcome#index'

  namespace :admin do
    root 'welcome#index'
    resources :packages
    resources :statuses
    resources :senders
    resources :roles
    resources :users
    resources :settings
  end

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  belongs_to :user
  belongs_to :role
end

app/models/package.rb
class Package < ActiveRecord::Base
	belongs_to :user
	belongs_to :sender
	has_many :statuses
	validates :reference, :track, presence: true
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :assignments
  has_many :users, :through => :assignments
end

app/models/sender.rb
class Sender < ActiveRecord::Base
	has_many :packages
	validates :name, :description, presence: true
end

app/models/setting.rb
class Setting < ActiveRecord::Base
end

app/models/status.rb
class Status < ActiveRecord::Base
	belongs_to :package
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :profile, dependent: :destroy
  has_many :assignments, dependent: :destroy
  has_many :roles, :through => :assignments
  has_many :packages	
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  after_create :create_profile

	def has_role?(role_sym)
  		roles.any? { |r| r.name.underscore.to_sym == role_sym }
	end

  private

  def create_profile
    Profile.create(user_id: self.id)
  end
	         
end

app/controllers/admin/settings_controller.rb
class Admin::SettingsController < ApplicationController
  before_action :set_setting, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @settings = Setting.all
    respond_with(@settings)
  end

  def show
    respond_with(@setting)
  end

  def new
    @setting = Setting.new
    respond_with(@setting)
  end

  def edit
  end

  def create
    @setting = Setting.new(setting_params)
    flash[:notice] = 'Setting was successfully created.' if @setting.save
    respond_with(:admin, @setting)
  end

  def update
    flash[:notice] = 'Setting was successfully updated.' if @setting.update(setting_params)
    respond_with(:admin, @setting)
  end

  def destroy
    @setting.destroy
    respond_with(@setting)
  end

  private
    def set_setting
      @setting = Setting.find(params[:id])
    end

    def setting_params
      params.require(:setting).permit(:company_name)
    end
end

app/controllers/packages_controller.rb
class PackagesController < ApplicationController
  before_action :set_package, only: [:show, :edit, :update, :destroy]

  respond_to :html, :json

  def index
    @packages = current_user.packages
    respond_with(@packages)
  end

  def show
    @statuses = @package.statuses.order(date: :desc)    
    respond_with(@package)
  end

  def new
    @package = Package.new
    respond_with(@package)
  end

  def edit
  end

  def create
    @package = Package.new(package_params)
    flash[:notice] = 'Package was successfully created.' if @package.save
    respond_with(@package)
  end

  def update
    flash[:notice] = 'Package was successfully updated.' if @package.update(package_params)
    respond_with(@package)
  end

  def destroy
    @package.destroy
    respond_with(@package)
  end

  private
    def set_package
      @package = Package.find(params[:id])
    end

    def package_params
      params.require(:package).permit(:reference, :track, :date_received)
    end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @roles = Role.all
    respond_with(@roles)
  end

  def show
    respond_with(@role)
  end

  def new
    @role = Role.new
    respond_with(@role)
  end

  def edit
  end

  def create
    @role = Role.new(role_params)
    flash[:notice] = 'Role was successfully created.' if @role.save
    respond_with(@role)
  end

  def update
    flash[:notice] = 'Role was successfully updated.' if @role.update(role_params)
    respond_with(@role)
  end

  def destroy
    @role.destroy
    respond_with(@role)
  end

  private
    def set_role
      @role = Role.find(params[:id])
    end

    def role_params
      params.require(:role).permit(:name)
    end
end

app/controllers/senders_controller.rb
class SendersController < ApplicationController
  before_action :set_sender, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @senders = Sender.all
    respond_with(@senders)
  end

  def show
    respond_with(@sender)
  end

  def new
    @sender = Sender.new
    respond_with(@sender)
  end

  def edit
  end

  def create
    @sender = Sender.new(sender_params)
    flash[:notice] = 'Sender was successfully created.' if @sender.save
    respond_with(@sender)
  end

  def update
    flash[:notice] = 'Sender was successfully updated.' if @sender.update(sender_params)
    respond_with(@sender)
  end

  def destroy
    @sender.destroy
    respond_with(@sender)
  end

  private
    def set_sender
      @sender = Sender.find(params[:id])
    end

    def sender_params
      params.require(:sender).permit(:name, :description)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def company_name
		Setting.first.company_name
	end	
end

app/helpers/packages_helper.rb
module PackagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/senders_helper.rb
module SendersHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/settings/_form.html.erb
<%= form_for([:admin, @setting]) do |f| %>
  <% if @setting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@setting.errors.count, "error") %> prohibited this setting from being saved:</h2>

      <ul>
      <% @setting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :company_name %><br>
    <%= f.text_field :company_name, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit 'Save', :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/settings/edit.html.erb
<h1 class="page-header">Settings</h1>

<%= render 'form' %>

app/views/admin/settings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Settings</h1>

<table>
  <thead>
    <tr>
      <th>Company name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @settings.each do |setting| %>
      <tr>
        <td><%= setting.company_name %></td>
        <td><%= link_to 'Show', setting %></td>
        <td><%= link_to 'Edit', edit_setting_path(setting) %></td>
        <td><%= link_to 'Destroy', setting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Setting', new_setting_path %>

app/views/admin/settings/new.html.erb
<h1>New Setting</h1>

<%= render 'form' %>

<%= link_to 'Back', settings_path %>

app/views/admin/settings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Company name:</strong>
  <%= @setting.company_name %>
</p>