config/routes.rb
Rails.application.routes.draw do

  resources :profiles

  resources :senders
  resources :roles
  resources :statuses
  resources :packages

  devise_for :users

  root 'welcome#index'

  namespace :admin do
    root 'welcome#index'
    resources :packages
    resources :statuses
    resources :senders
    resources :roles
    resources :users
    resources :settings
  end

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  belongs_to :user
  belongs_to :role
end

app/models/package.rb
class Package < ActiveRecord::Base
	belongs_to :user
	belongs_to :sender
	has_many :statuses
	validates :reference, :track, presence: true
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :assignments
  has_many :users, :through => :assignments
end

app/models/sender.rb
class Sender < ActiveRecord::Base
	has_many :packages
	validates :name, :description, presence: true
end

app/models/setting.rb
class Setting < ActiveRecord::Base
end

app/models/status.rb
class Status < ActiveRecord::Base
	belongs_to :package
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :profile, dependent: :destroy
  has_many :assignments, dependent: :destroy
  has_many :roles, :through => :assignments
  has_many :packages	
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  after_create :create_profile

	def has_role?(role_sym)
  		roles.any? { |r| r.name.underscore.to_sym == role_sym }
	end

  private

  def create_profile
    Profile.create(user_id: self.id)
  end
	         
end

app/controllers/admin/statuses_controller.rb
class Admin::StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @statuses = Status.all
    respond_with(@statuses)
  end

  def show
    respond_with(@status)
  end

  def new
    @status = Status.new
    respond_with(@status)
  end

  def edit
  end

  def create
    @status = Status.new(status_params)
    flash[:notice] = 'Status was successfully created.' if @status.save
    respond_with(:admin, @status.package)
  end

  def update
    flash[:notice] = 'Status was successfully updated.' if @status.update(status_params)
    respond_with(@status)
  end

  def destroy
    @status.destroy
    respond_with(@status)
  end

  private
    def set_status
      @status = Status.find(params[:id])
    end

    def status_params
      params.require(:status).permit(:package_id, :date, :status, :comments)
    end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @roles = Role.all
    respond_with(@roles)
  end

  def show
    respond_with(@role)
  end

  def new
    @role = Role.new
    respond_with(@role)
  end

  def edit
  end

  def create
    @role = Role.new(role_params)
    flash[:notice] = 'Role was successfully created.' if @role.save
    respond_with(@role)
  end

  def update
    flash[:notice] = 'Role was successfully updated.' if @role.update(role_params)
    respond_with(@role)
  end

  def destroy
    @role.destroy
    respond_with(@role)
  end

  private
    def set_role
      @role = Role.find(params[:id])
    end

    def role_params
      params.require(:role).permit(:name)
    end
end

app/controllers/senders_controller.rb
class SendersController < ApplicationController
  before_action :set_sender, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @senders = Sender.all
    respond_with(@senders)
  end

  def show
    respond_with(@sender)
  end

  def new
    @sender = Sender.new
    respond_with(@sender)
  end

  def edit
  end

  def create
    @sender = Sender.new(sender_params)
    flash[:notice] = 'Sender was successfully created.' if @sender.save
    respond_with(@sender)
  end

  def update
    flash[:notice] = 'Sender was successfully updated.' if @sender.update(sender_params)
    respond_with(@sender)
  end

  def destroy
    @sender.destroy
    respond_with(@sender)
  end

  private
    def set_sender
      @sender = Sender.find(params[:id])
    end

    def sender_params
      params.require(:sender).permit(:name, :description)
    end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @statuses = Status.all
    respond_with(@statuses)
  end

  def show
    respond_with(@status)
  end

  def new
    @status = Status.new
    respond_with(@status)
  end

  def edit
  end

  def create
    @status = Status.new(status_params)
    flash[:notice] = 'Status was successfully created.' if @status.save
    respond_with(@status)
  end

  def update
    flash[:notice] = 'Status was successfully updated.' if @status.update(status_params)
    respond_with(@status)
  end

  def destroy
    @status.destroy
    respond_with(@status)
  end

  private
    def set_status
      @status = Status.find(params[:id])
    end

    def status_params
      params.require(:status).permit(:date, :status, :comments)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def company_name
		Setting.first.company_name
	end	
end

app/helpers/packages_helper.rb
module PackagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/senders_helper.rb
module SendersHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/statuses/_form.html.erb
<div class="modal-body">

<%= form_for([:admin, @status]) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :package_id, value: @package.id %>

  <div class="form-group form-inline">
    <%= f.label t('packages.date_status') %><br>
    <%= f.datetime_select :date, {}, { class: "form-control" } %>
  </div>
  <div class="form-group">
    <%= f.label t('packages.status') %><br>
    <%= f.text_field :status, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label t('packages.status_comments') %><br>
    <%= f.text_area :comments, class: "form-control" %>
  </div>
</div>

<div class="modal-footer">
  <button type="button" class="btn btn-default" data-dismiss="modal"><%= t('packages.close') %></button>
  <%= f.submit t('packages.create_status'), :class => 'btn btn-primary' %>
</div>  
<% end %>

app/views/admin/statuses/edit.html.erb
<h1>Editing Status</h1>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/admin/statuses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Statuses</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Status</th>
      <th>Comments</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @statuses.each do |status| %>
      <tr>
        <td><%= status.date %></td>
        <td><%= status.status %></td>
        <td><%= status.comments %></td>
        <td><%= link_to 'Show', status %></td>
        <td><%= link_to 'Edit', edit_status_path(status) %></td>
        <td><%= link_to 'Destroy', status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Status', new_status_path %>

app/views/admin/statuses/new.html.erb
<h1>New Status</h1>

<%= render 'form' %>

<%= link_to 'Back', statuses_path %>

app/views/admin/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @status.date %>
</p>

<p>
  <strong>Status:</strong>
  <%= @status.status %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @status.comments %>
</p>

<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/_form.html.erb
<%= form_for(@status) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label t('packages.date_status') %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label t('packages.status') %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label t('packages.status_comments') %><br>
    <%= f.text_area :comments %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<h1>Editing Status</h1>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Statuses</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Status</th>
      <th>Comments</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @statuses.each do |status| %>
      <tr>
        <td><%= status.date %></td>
        <td><%= status.status %></td>
        <td><%= status.comments %></td>
        <td><%= link_to 'Show', status %></td>
        <td><%= link_to 'Edit', edit_status_path(status) %></td>
        <td><%= link_to 'Destroy', status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Status', new_status_path %>

app/views/statuses/new.html.erb
<h1>New Status</h1>

<%= render 'form' %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @status.date %>
</p>

<p>
  <strong>Status:</strong>
  <%= @status.status %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @status.comments %>
</p>

<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>